SampleApp::Application.routes.draw do |map|
  get "sessions/new"

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  #get "users/new" # auto generated by the User controller generation script

  
#  Page	     URL	        Named route    controller   action    
#  --------  --------     -----------    ----------   --------
#  Home	     /	          root_path      pages        home
#  About	   /about	      about_path     pages        about
#  Contact	 /contact	    contact_path   pages        contact
#  Help	     /help	      help_path      pages        help
#  Sign up	 /signup	    signup_path    
#  Sign in	 /signin	    signin_path


#  HTTPr  URL           Action  Named route       Purpose
#  -----  ------------  ------  ----------------  ---------------------------------
#  GET    /users        index   users_path        page to list all users
#  GET    /users/1      show    user_path(1)      page to show user with id 1
#  GET    /users/new    new     new_user_path     page to make a new user (signup)
#  POST   /users        create  users_path        create a new user
#  GET    /users/1/edit edit    edit_user_path(1) page to edit user with id 1
#  PUT    /users/1      update  user_path(1)      update user with id 1
#  DELETE /users/1      destroy user_path(1)      delete user with id 1#




#  note: helpers created are <>_path = /match_name
#                            <>_url  = url/match_name
  
  # session sign-up/in/out
  match '/signup',  :to => 'users#new',     :as => :signup
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  match '/contact', :to => 'pages#contact', :as => :contact
  match '/about',   :to => 'pages#about',   :as => :about
  match '/help',    :to => 'pages#help',    :as => :help

  root              :to => "pages#home"
  
#  get "pages/home"
#  get "pages/contact"
#  get "pages/about"
#  get "pages/help"

  # The priority is based upon order of creation:
  # first created -> highest priority.

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get :short
  #       post :toggle
  #     end
  #
  #     collection do
  #       get :sold
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get :recent, :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => "welcome#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end
